### ISSUE TITLE
Feedback on the update 4.2 and 4.3

### ISSUE THREAD

**Issue by arutemu** [djshaji/amp-rack#69]
Hello Mr. Shaji, and thank you for the update!

As usual, there are good news and bad news about the update.

1) Good - new IR plugins *work*. As I am not exactly sure how Impulse response convolved works under the hood, I could say that different impulse IDs produce slightly different sound effects.

2) Bad - the NAM plugin stopped working.
To be more exact, a user can't load NAM models from the storage, all options (.nam & .zip files) are grayed out and not selectable.

I haven't checked most of the other functionality, so I will update this thread in case of newfound issues.

**Comment by arutemu** [comment]
Hallo Mr. Shaji! And thank you again for the new update!

I am glad to report that in ver 4.3:
1) New AIDA plugin is working (checked with a bunch of random .json models)
2) The issue with selecting NAM models is also fixed and the plugin is usable again.

**Comment by arutemu** [comment]
However, as usual, I have found a few new issues as well 😅
Talking about ver. 4.3 of course.
One is an actual bug, the other one is more like a polish for the new plugins.

1) The model selection dialog (which opens built-in Android file explorer to select NAM/AIDA models) has a new issue - now all files are available to be selected, with no regard to the file types.
- That means that the user can accidentally select any non-model file (.jpg picture, for example), and it will be selected as the model.
- ⚠ Of course, it wouldn't work, and the app will crash shortly after selection.
- After that, the user won't be able to start the app again without clearing all app data.

2) The selected model files for both NAM and AIDA plugins are not saved in user-created presets.
- That means that all presets with those plugins do not save the model, and the user will need to reselect the model file every time he loads the preset.

**Comment by djshaji** [comment]
Hi, just published an update fixing all of the above. Thanks for pointing it out. I really appreciate it :+1:

**Comment by arutemu** [comment]
Thank you for the update, Mr. Shaji!
I have checked the new version, and all of the issues above are fixed now.

**Comment by djshaji** [comment]
Hi, I've implemented a few latency optimizations in this release:
https://github.com/djshaji/amp-rack/releases/tag/4.33

Please do check and report if latency seems or is reported lower than before

Thanks :+1:

**Comment by arutemu** [comment]
Hello again Mr. Shaji!

I've checked the updated version 4.33 and have noted the latency using different plugins and presets.

I've also checked the same latency menu in version 4.32 to compare the results.
Please clarify what each value means here (Like tuner and Xruns)

4.33:
Latency stays within 1-3ms in all my checks.
Buffer size stays on 192/96
And Xruns vary from 0/1 up to 0/20.
![Screenshot_20240603_123536_Amp Rack](https://github.com/djshaji/amp-rack/assets/6502628/0fb8b8f9-eab0-4329-b2b5-cd6d8dec77ad)

4.32:
In all cases, Tuner and Xruns stayed on 0/0 value.
The buffer size is 192/192.
![Screenshot_20240603_124515_Amp Rack](https://github.com/djshaji/amp-rack/assets/6502628/4b2d36de-15c0-4cea-bfb7-73308b3c3208)

**Comment by arutemu** [comment]
Oh, and I also have to note that aside from the latency values, there is no noticeable difference in the audio itself. There is no perceptible delay between the input and the output signal.
